import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body cz-shortcut-listen="false" className={inter.className}>
				<div>
					<div>sidebar</div>
					<div className="flex  flex-col gap-4">
						<Link href={'/?pageNumber=1'}>Main</Link>
						<Link href={'/user?pageNumber=1'}>User</Link>
						<Link href={'/books?pageNumber=1'}>Book</Link>
					</div>
				</div>
				{children}
			</body>
		</html>
	);
}
