export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};
import '../globals.css';
import Link from 'next/link';

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<Link href={'/'}>Main</Link>

				{children}
			</body>
		</html>
	);
}
